### ISSUE TITLE
Need to log in from the extension when already logged in to Kyso

### ISSUE THREAD

**Issue by KyleOS** [kyso-io/jupyterlab-extension#16]
In a Kyso workspace

**Comment by zouhx11** [comment]
I see fix, but how to update this extension? or directly install from this github repository

**Comment by KyleOS** [comment]
@zouhx11 are you using the extension on your own server? This issue is for when launching Jupyterlab on Kyso. So you should not need to log in again in that workspace to publish to Kyso. If you've launched Jupyterlab locally or on another cloud provider you will need to log in to Kyso from the extension.

**Comment by zouhx11** [comment]
@KyleOS yes I've launched Jupyterlab locally, and I face the same problem when I log in to Kyso. I thought the recent fix was for all situations.

**Comment by zouhx11** [comment]
@KyleOS In fact, I just test the publish plugin on kyso jupyterlab workspace, it doesn't work either.

**Comment by KyleOS** [comment]
@zouhx11 can you try again with a new workspace? It could be that the fix wasn't pushed to existing workspaces. I've tested it myself now and everything is running just fine.
