### ISSUE TITLE
Posts not rendering on Kyso when published from the extension 

### ISSUE THREAD

**Issue by KyleOS** [kyso-io/jupyterlab-extension#17]
Is this our issue or the way they're posting?

[https://kyso.io/benjamin/working](https://kyso.io/benjamin/working)

[https://kyso.io/sazack/la-parking-violation-explorer-and-recommendations](https://kyso.io/sazack/la-parking-violation-explorer-and-recommendations)

[https://kyso.io/anshulshah957/jupyter-notebook-test](https://kyso.io/anshulshah957/jupyter-notebook-test)

**Comment by eoinmurray** [comment]
they are just empty or full of only code - but we should say something

**Comment by KyleOS** [comment]
No if you look at the posts there isn't even an option to toggle the code.
